Use minitest to replace test/unit.
When I tried to run rake newb, I get following error:

MiniTest::Unit::TestCase is now Minitest::Test. From /Users/Juan/.rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit/testcase.rb:8:in `<module:Unit>'
/Users/Juan/.rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:676:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
  from /Users/Juan/.rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:261:in `<module:Unit>'
  from /Users/Juan/.rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:15:in `<module:Test>'
  from /Users/Juan/.rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:7:in `<top (required)>'
  from /Users/Juan/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/Juan/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/Juan/dev/benchmark-ips/test/test_benchmark_ips.rb:1:in `<top (required)>'
  from /Users/Juan/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/Juan/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from -e:1:in `<main>'
rake aborted!
Command failed with status (1): [/Users/Juan/.rubies/ruby-2.1.2/bin/ruby -w...]
/Users/Juan/.gem/ruby/2.1.2/gems/hoe-3.12.0/lib/hoe/test.rb:83:in `block in define_test_tasks'
Tasks: TOP => newb => default => test
(See full trace by running task with --trace)

But the error gone after switch to minitest.