Fixed broken gemspec
`.gemtest` doesn't exist:
$ gem build benchmark-ips.gemspec
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    [".gemtest"] are not files